language: python
python:
# - "2.7"
- "3.4"
- "3.5"
- "3.6"
virtual_env:
  system_site_packages: true
install:
- pip install --upgrade pip
- pip install -r requirements.txt
script:
  pytest --cov=pycnab240
after_success:
  coveralls
